# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/C/LSM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/C/LSM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/C/LSM/CMakeFiles /home/alex/C/LSM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/C/LSM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lsm

# Build rule for target.
lsm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lsm
.PHONY : lsm

# fast build rule for target.
lsm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsm.dir/build.make CMakeFiles/lsm.dir/build
.PHONY : lsm/fast

#=============================================================================
# Target rules for targets named calc

# Build rule for target.
calc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calc
.PHONY : calc

# fast build rule for target.
calc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/build
.PHONY : calc/fast

sources/SLE/SLE.o: sources/SLE/SLE.c.o
.PHONY : sources/SLE/SLE.o

# target to build an object file
sources/SLE/SLE.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsm.dir/build.make CMakeFiles/lsm.dir/sources/SLE/SLE.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/sources/SLE/SLE.c.o
.PHONY : sources/SLE/SLE.c.o

sources/SLE/SLE.i: sources/SLE/SLE.c.i
.PHONY : sources/SLE/SLE.i

# target to preprocess a source file
sources/SLE/SLE.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsm.dir/build.make CMakeFiles/lsm.dir/sources/SLE/SLE.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/sources/SLE/SLE.c.i
.PHONY : sources/SLE/SLE.c.i

sources/SLE/SLE.s: sources/SLE/SLE.c.s
.PHONY : sources/SLE/SLE.s

# target to generate assembly for a file
sources/SLE/SLE.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsm.dir/build.make CMakeFiles/lsm.dir/sources/SLE/SLE.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/sources/SLE/SLE.c.s
.PHONY : sources/SLE/SLE.c.s

sources/gnuplot/gnuplot.o: sources/gnuplot/gnuplot.c.o
.PHONY : sources/gnuplot/gnuplot.o

# target to build an object file
sources/gnuplot/gnuplot.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsm.dir/build.make CMakeFiles/lsm.dir/sources/gnuplot/gnuplot.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/sources/gnuplot/gnuplot.c.o
.PHONY : sources/gnuplot/gnuplot.c.o

sources/gnuplot/gnuplot.i: sources/gnuplot/gnuplot.c.i
.PHONY : sources/gnuplot/gnuplot.i

# target to preprocess a source file
sources/gnuplot/gnuplot.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsm.dir/build.make CMakeFiles/lsm.dir/sources/gnuplot/gnuplot.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/sources/gnuplot/gnuplot.c.i
.PHONY : sources/gnuplot/gnuplot.c.i

sources/gnuplot/gnuplot.s: sources/gnuplot/gnuplot.c.s
.PHONY : sources/gnuplot/gnuplot.s

# target to generate assembly for a file
sources/gnuplot/gnuplot.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsm.dir/build.make CMakeFiles/lsm.dir/sources/gnuplot/gnuplot.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/sources/gnuplot/gnuplot.c.s
.PHONY : sources/gnuplot/gnuplot.c.s

sources/lsm/lsm.o: sources/lsm/lsm.c.o
.PHONY : sources/lsm/lsm.o

# target to build an object file
sources/lsm/lsm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsm.dir/build.make CMakeFiles/lsm.dir/sources/lsm/lsm.c.o
.PHONY : sources/lsm/lsm.c.o

sources/lsm/lsm.i: sources/lsm/lsm.c.i
.PHONY : sources/lsm/lsm.i

# target to preprocess a source file
sources/lsm/lsm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsm.dir/build.make CMakeFiles/lsm.dir/sources/lsm/lsm.c.i
.PHONY : sources/lsm/lsm.c.i

sources/lsm/lsm.s: sources/lsm/lsm.c.s
.PHONY : sources/lsm/lsm.s

# target to generate assembly for a file
sources/lsm/lsm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsm.dir/build.make CMakeFiles/lsm.dir/sources/lsm/lsm.c.s
.PHONY : sources/lsm/lsm.c.s

sources/main.o: sources/main.c.o
.PHONY : sources/main.o

# target to build an object file
sources/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/sources/main.c.o
.PHONY : sources/main.c.o

sources/main.i: sources/main.c.i
.PHONY : sources/main.i

# target to preprocess a source file
sources/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/sources/main.c.i
.PHONY : sources/main.c.i

sources/main.s: sources/main.c.s
.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/sources/main.c.s
.PHONY : sources/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... calc"
	@echo "... lsm"
	@echo "... sources/SLE/SLE.o"
	@echo "... sources/SLE/SLE.i"
	@echo "... sources/SLE/SLE.s"
	@echo "... sources/gnuplot/gnuplot.o"
	@echo "... sources/gnuplot/gnuplot.i"
	@echo "... sources/gnuplot/gnuplot.s"
	@echo "... sources/lsm/lsm.o"
	@echo "... sources/lsm/lsm.i"
	@echo "... sources/lsm/lsm.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

